version: '2'
services:
  web:
    build: ./nginx
    image: erald/nginx
    ports:
      - "8080:80"
    volumes:
      - ./www/default/site:/var/www
      - ./www/default/config/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
    links:
      - php

  php:
    image: nmcteam/php56
    volumes:
      - ./www/default/config/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
      - ./www/default/site:/var/www
    links:
      - mysql

  mysql:
    image: mysql:latest
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: symfony
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
